# pytest.ci.ini
[pytest]
minversion = 6.0

# Less verbose output for CI, generate JUnit XML report
addopts = -ra --tb=short --strict-markers --junitxml=tests/backend_test_results.xml
testpaths = tests
markers =
    crud: mark a test as a crud test.
    users: mark a test as a user test.
    plans: mark test as related to plans.
    routes: route calculation tests.
    friendships: tests for friendship functionality.
    
    actions: mark a test as an action test.
    content: mark a test as a content test.
    auth: mark a test as an auth test.
    